无量纲化
中心化(zero-centerd)
当数据按照最小值中性化后，在按极差缩放，数据移动了最小值单位，收敛到[0,1] 之间，这个过程叫归一化

In [1]:
# 归一化
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
data = [[-1.0, 2.0], [-0.5, 6.0], [0.0, 10.0], [1.0, 18.0]]
pd.DataFrame(data)
scaler = MinMaxScaler()
# 归一化到[0,1]区间, 数据太大使用partition_fit_transform
data_s = scaler.fit_transform(data)


# 第2列的2范数
data = np.array(data)
n = np.linalg.norm(data[:, 1], ord=2)
data_s,6/n


(array([[0.  , 0.  ],
        [0.25, 0.25],
        [0.5 , 0.5 ],
        [1.  , 1.  ]]),
 np.float64(0.2785430072655778))

In [13]:
# 标准化
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
data = [[-1.0, 2.0], [-0.5, 6.0], [0.0, 10.0], [1.0, 18.0]]
scaler = StandardScaler()
# 标准化到均值为0，方差为1
data_s = scaler.fit_transform(data)
scaler.mean_, scaler.var_
data_s

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [4]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

data = pd.DataFrame({'color': ['red', 'blue', 'green', 'blue', 'red']})
data['color'] = data['color'].astype('category')
encoder = LabelEncoder()
data['color'] = encoder.fit_transform(data['color'])
encoder.classes_

array(['blue', 'green', 'red'], dtype=object)

In [ ]:
# 很多时候，特征中的值，并不具备大小关系，所以使用独热编码更加准确
from sklearn.preprocessing import OneHotEncoder

import pandas as pd
import numpy as np

data = pd.DataFrame({'color': ['red', 'blue', 'green', 'blue', 'red']})
enc = OneHotEncoder(categories="auto").fit(data[['color']])

result = enc.transform(data[['color']])
result.toarray()


AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names'

In [ ]:
# 二值化， 处理特征
from sklearn.preprocessing import Binarizer
import pandas as pd
import numpy as np
data = [[-1.0, 2.0], [-0.5, 6.0], [0.0, 10.0], [1.0, 18.0]]
# 大于为1，小于为0
scaler = Binarizer(threshold=0.5)
# 二值化
data_s = scaler.fit_transform(data)
data_s

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.]])

In [6]:
# 分箱，处理特征，将数据分为几个段，返回段的索引
from sklearn.preprocessing import KBinsDiscretizer
import pandas as pd
import numpy as np
data = [[-1.0, 2.0], [-0.5, 6.0], [0.0, 10.0], [1.0, 18.0]]
# 分成3个箱子，使用均匀分布
scaler = KBinsDiscretizer(n_bins=3, encode='onehot', strategy='uniform')
# 分箱
data_s = scaler.fit_transform(data)
data_s.toarray(), scaler.n_bins_, scaler.bin_edges_

(array([[1., 0., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1.]]),
 array([3, 3]),
 array([array([-1.        , -0.33333333,  0.33333333,  1.        ]),
        array([ 2.        ,  7.33333333, 12.66666667, 18.        ])],
       dtype=object))